#!/bin/sh
set -e
# set -x

main() {
  [ "$(id -u)" -eq 0 ] || die "must be run as root"

  mkdir -p /Library/Application\ Support/sslayer
  cd /Library/Application\ Support/sslayer || exit 1

  case "$1" in
    setup) setup ;;
    start) server "$2" ;;
    *) die "usage: slayer [setup | server path/to/nginx]" ;;
  esac
}

die() {
  echo "$*"
  exit 1
}

setup() {
  if [ ! -r cert.pem ]; then
    echo "Generating *.goodeggs.test wildcard cert:"
  cat > openssl.conf <<EOF
[ req ]
distinguished_name = subject
req_extensions      = req_ext
x509_extensions     = x509_ext

[ subject ]
countryName = Country Name (2-letter code)
countryName_default = US
stateOrProvinceName = State or Province Name (full name)
stateOrProvinceName_default = California
localityName = Locality Name (e.g. city)
localityName_default = San Francisco
organizationName = Organization Name
organizationName_default = Good Eggs
organizationalUnitName = Organization Unit
organizationalUnitName_default = Local Development
commonName = Common Name
commonName_default = *.goodeggs.test

[ req_ext ]
subjectAltName = @alternate_names

[ x509_ext ]
subjectAltName = @alternate_names

[ alternate_names ]
DNS.1 = *.goodeggs.test
EOF
    openssl req -batch -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 3650 -sha256 -nodes -config openssl.conf | sed 's//    /'
    echo ""
    echo "Now, I will open $PWD/cert.pem in Keychain Access, and you need to make sure SSL is set to Always Trust."
    printf "Ready? [Y] "
    read -r
    open cert.pem
  else
    die "$PWD/cert.pem already exists.  You only need to do this setup once per machine.  Delete $PWD and re-run if you really want to re-install."
  fi
}

server() {
  path_to_nginx="$1"

  MAPPINGS=$(cat <<EOF
api.goodeggs.test:3000
www.goodeggs.test:3000
mobile-api.goodeggs.test:3003
manage.goodeggs.test:3010
ops.goodeggs.test:8000
ops-employees.goodeggs.test:8005
employees.goodeggs.test:8005
ops-employees-api.goodeggs.test:8010
employees-api.goodeggs.test:8010
ops-purchase-orders.goodeggs.test:8025
purchase-orders.goodeggs.test:8025
ops-purchase-orders-api.goodeggs.test:8030
purchase-orders-api.goodeggs.test:8030
inventory-api.goodeggs.test:8040
inventory.goodeggs.test:8045
customers-api.goodeggs.test:8050
availability-api.goodeggs.test:8060
domain-events.goodeggs.test:9000
demand-prediction-api.goodeggs.test:8090
pick-api.goodeggs.test:9010
shipping-api.goodeggs.test:9020
fulfillment.goodeggs.test:9030
fulfillment-options-api.goodeggs.test:9040
it-accounts-ui.goodeggs.test:9050
it-accounts-api.goodeggs.test:9060
pick-triage-api.goodeggs.test:9070
pick-triage.goodeggs.test:9075
gather.goodeggs.test:9085
devices.goodeggs.test:9095
merchandising.goodeggs.test:9100
catalog-api.goodeggs.test:9130
EOF
)

  cat > nginx.conf <<EOF
daemon off;
worker_processes auto;

events {
    worker_connections  1024;
}

http {
    default_type  application/octet-stream;

    ssl_certificate     "$PWD/cert.pem";
    ssl_certificate_key "$PWD/key.pem";

    server {
    	listen 80 default_server;
    	server_name _;
    	return 301 https://\$host\$request_uri;
    }
EOF

  idx=0
  for entry in $MAPPINGS; do
    idx=$((idx + 1))
    hostname=$(echo "$entry" | awk -F: '{print $1}')
    port=$(echo "$entry" | awk -F: '{print $2}')

    cat >> nginx.conf <<EOF

    upstream u${idx} {
        server 127.0.0.1:${port};
    }

    server {
        listen 443 ssl;
        server_name ${hostname};
        location / {
            proxy_pass http://u${idx};
            proxy_set_header Host \$host;
            proxy_set_header X-Real-IP \$remote_addr;
            proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto \$scheme;
            proxy_set_header Fastly-SSL 1;
        }
    }
EOF
  done

  echo '}' >> nginx.conf

  echo "starting nginx!"
  exec "$path_to_nginx" -c "$PWD/nginx.conf"
}

main "$@"
